local registry = require("nautilus.custom.template-registry")

local M = {}

local function substitute(value, ctx)
	if type(value) ~= "string" then return value end
	return (value:gsub("{{([%w_]+)}}", function(key)
		local v = ctx[key]
		if v == nil then return "" end
		return tostring(v)
	end))
end

local function read_input(prompt, default)
	local suffix = default and default ~= "" and (" [" .. default .. "]") or ""
	local val = vim.fn.input(prompt .. suffix .. ": ")
	if val == "" then return default or "" end
	return val
end

local function bool_input(prompt, default)
	local def = default and "Y/n" or "y/N"
	local val = vim.fn.input(prompt .. " [" .. def .. "]: ")
	if val == "" then return default == true end
	val = val:lower()
	return val == "y" or val == "yes" or val == "true" or val == "1"
end

local function collect_context(template, overrides)
	overrides = overrides or {}
	local ctx = {}

	for _, prompt in ipairs(template.prompts or {}) do
		if overrides[prompt.key] ~= nil then
			ctx[prompt.key] = overrides[prompt.key]
		else
			local default = substitute(prompt.default, ctx)
			if prompt.type == "boolean" then
				ctx[prompt.key] = bool_input(prompt.label, default == true)
			else
				ctx[prompt.key] = read_input(prompt.label, default)
			end
		end

		if prompt.required and (ctx[prompt.key] == nil or tostring(ctx[prompt.key]) == "") then
			return nil, ("Prompt '%s' is required"):format(prompt.key)
		end
	end

	ctx.project_name = ctx.project_name or "project"
	ctx.target_dir = substitute(ctx.target_dir or ("./" .. ctx.project_name), ctx)
	ctx.abs_target_dir = vim.fn.fnamemodify(ctx.target_dir, ":p")
	ctx.app_display_name = substitute(ctx.app_display_name or ctx.project_name, ctx)
	ctx.license = ctx.license or "MIT"
	ctx.author = ctx.author or ""
	return ctx
end

local function ensure_writable_dir(path)
	if vim.fn.isdirectory(path) == 0 then return true end
	local entries = vim.fn.readdir(path)
	return vim.tbl_isempty(entries)
end

local function write_file(path, lines)
	local dir = vim.fn.fnamemodify(path, ":h")
	vim.fn.mkdir(dir, "p")
	vim.fn.writefile(lines, path)
end

local function run_system(cmd, cwd)
	local result = vim.system(cmd, { cwd = cwd, text = true }):wait()
	if result.code ~= 0 then
		local err = result.stderr ~= "" and result.stderr or result.stdout
		return false, vim.trim(err)
	end
	return true, vim.trim(result.stdout)
end

local function plan_node_js(ctx)
	local package_json = {
		"{",
		("  \"name\": \"%s\","):format(ctx.project_name),
		"  \"version\": \"0.1.0\",",
		"  \"private\": true,",
		("  \"author\": \"%s\","):format(ctx.author),
		("  \"license\": \"%s\","):format(ctx.license),
		"  \"type\": \"module\",",
		"  \"scripts\": {",
		"    \"start\": \"node src/index.js\",",
		"    \"dev\": \"node --watch src/index.js\",",
		"    \"test\": \"node --test\"",
		"  }",
		"}",
	}

	return {
		files = {
			{ path = "package.json", lines = package_json },
			{ path = ".gitignore", lines = { "node_modules", "dist", ".DS_Store" } },
			{ path = "README.md", lines = { "# " .. ctx.project_name, "", "Generated by Nautilus TemplateNew." } },
			{ path = "src/index.js", lines = { "console.log('Hello from " .. ctx.project_name .. "');" } },
		},
		commands = ctx.install_deps and { { "npm", "install" } } or {},
		expected = { "package.json", "src/index.js" },
	}
end

local function plan_cmake_cpp(ctx)
	return {
		files = {
			{
				path = "CMakeLists.txt",
				lines = {
					"cmake_minimum_required(VERSION 3.20)",
					("project(%s LANGUAGES CXX)"):format(ctx.project_name),
					"",
					("set(CMAKE_CXX_STANDARD %s)"):format(ctx.cpp_standard),
					"set(CMAKE_CXX_STANDARD_REQUIRED ON)",
					"",
					("add_executable(%s src/main.cpp)"):format(ctx.project_name),
				},
			},
			{
				path = "src/main.cpp",
				lines = {
					"#include <iostream>",
					"",
					"int main() {",
					("  std::cout << \"Hello from %s\\n\";"):format(ctx.project_name),
					"  return 0;",
					"}",
				},
			},
			{ path = "README.md", lines = { "# " .. ctx.project_name, "", "Generated by Nautilus TemplateNew." } },
		},
		commands = {},
		expected = { "CMakeLists.txt", "src/main.cpp" },
	}
end

local function patch_forge(ctx)
	local package_path = ctx.abs_target_dir .. "/package.json"
	if vim.fn.filereadable(package_path) == 0 then return false, "forge scaffold did not produce package.json" end

	local lines = vim.fn.readfile(package_path)
	for i, line in ipairs(lines) do
		if line:match('"name"%s*:') then lines[i] = ('  "name": "%s",'):format(ctx.project_name) end
		if line:match('"productName"%s*:') then lines[i] = ('  "productName": "%s",'):format(ctx.app_display_name) end
		if line:match('"author"%s*:') and ctx.author ~= "" then lines[i] = ('  "author": "%s",'):format(ctx.author) end
		if line:match('"license"%s*:') then lines[i] = ('  "license": "%s",'):format(ctx.license) end
	end
	vim.fn.writefile(lines, package_path)
	return true, nil
end

local function exec_forge(ctx, dry_run)
	local parent = vim.fn.fnamemodify(ctx.abs_target_dir, ":h")
	local name = vim.fn.fnamemodify(ctx.abs_target_dir, ":t")
	local scaffold_cmd = { "npm", "init", "electron-app@latest", name, "--", "--template=vite" }

	if dry_run then
		return {
			files = {},
			commands = { scaffold_cmd, { "patch", "package.json metadata" }, ctx.run_start_smoke and { "npm", "run", "start" } or nil },
			expected = { "package.json" },
		}
	end

	vim.fn.mkdir(parent, "p")
	local ok, err = run_system(scaffold_cmd, parent)
	if not ok then return nil, ("electron-forge scaffold failed: %s"):format(err) end

	local ok_patch, patch_err = patch_forge(ctx)
	if not ok_patch then return nil, patch_err end

	if ctx.run_start_smoke then
		local _, _ = run_system({ "npm", "run", "start" }, ctx.abs_target_dir)
	end

	return {
		files = {},
		commands = { scaffold_cmd },
		expected = { "package.json" },
	}
end

local function exec_rust(ctx, dry_run)
	local parent = vim.fn.fnamemodify(ctx.abs_target_dir, ":h")
	local name = vim.fn.fnamemodify(ctx.abs_target_dir, ":t")
	local cmd = { "cargo", "new", "--bin", name }

	if dry_run then
		return {
			files = { { path = "Cargo.toml" }, { path = "src/main.rs" } },
			commands = { cmd, { "patch", "Cargo.toml metadata" } },
			expected = { "Cargo.toml", "src/main.rs" },
		}
	end

	vim.fn.mkdir(parent, "p")
	local ok, err = run_system(cmd, parent)
	if not ok then return nil, ("cargo scaffold failed: %s"):format(err) end

	local cargo_path = ctx.abs_target_dir .. "/Cargo.toml"
	if vim.fn.filereadable(cargo_path) == 1 then
		local lines = vim.fn.readfile(cargo_path)
		local package_end = nil
		for i, line in ipairs(lines) do
			if i > 1 and line:match("^%[.+%]") then
				package_end = i - 1
				break
			end
		end
		if not package_end then package_end = #lines end

		if ctx.author ~= "" then table.insert(lines, package_end + 1, "authors = [\"" .. ctx.author .. "\"]") end
		table.insert(lines, package_end + 1, "license = \"" .. ctx.license .. "\"")
		vim.fn.writefile(lines, cargo_path)
	end

	return {
		files = {},
		commands = { cmd },
		expected = { "Cargo.toml", "src/main.rs" },
	}
end

function M.build_plan(template, ctx, dry_run)
	if template.id == "node-js-package" then return plan_node_js(ctx) end
	if template.id == "cmake-cpp-app" then return plan_cmake_cpp(ctx) end
	if template.id == "react-electron-js-forge" then return exec_forge(ctx, dry_run) end
	if template.id == "rust-bin" then return exec_rust(ctx, dry_run) end
	return nil, ("Unknown template id: %s"):format(template.id)
end

local function write_plan_files(plan, root)
	for _, file in ipairs(plan.files or {}) do
		local path = root .. "/" .. file.path
		write_file(path, file.lines or {})
	end
end

local function run_plan_commands(plan, root)
	for _, cmd in ipairs(plan.commands or {}) do
		if cmd and cmd[1] ~= "patch" then
			local ok, err = run_system(cmd, root)
			if not ok then return false, err end
		end
	end
	return true, nil
end

local function validate_expected(plan, root)
	for _, rel in ipairs(plan.expected or {}) do
		local path = root .. "/" .. rel
		if vim.fn.filereadable(path) == 0 and vim.fn.isdirectory(path) == 0 then
			return false, ("expected artifact missing: %s"):format(rel)
		end
	end
	return true, nil
end

function M.create(template_id, opts)
	opts = opts or {}
	local template = registry.get(template_id)
	if not template then return nil, ("Unknown template '%s'"):format(template_id) end

	local ctx, ctx_err = collect_context(template, opts.overrides)
	if not ctx then return nil, ctx_err end

	if not opts.dry_run and not ensure_writable_dir(ctx.abs_target_dir) then
		return nil, ("Target directory is not empty: %s"):format(ctx.abs_target_dir)
	end

	local plan, plan_err = M.build_plan(template, ctx, opts.dry_run == true)
	if not plan then return nil, plan_err end

	if opts.dry_run then
		return {
			template = template,
			context = ctx,
			plan = plan,
		}
	end

	vim.fn.mkdir(ctx.abs_target_dir, "p")
	write_plan_files(plan, ctx.abs_target_dir)

	local ok_cmd, cmd_err = run_plan_commands(plan, ctx.abs_target_dir)
	if not ok_cmd then return nil, cmd_err end

	local ok_expected, expected_err = validate_expected(plan, ctx.abs_target_dir)
	if not ok_expected then return nil, expected_err end

	return {
		template = template,
		context = ctx,
		plan = plan,
	}, nil
end

return M
