return require("nautilus.custom.colorscheme").lazy_setup({
	{
		"folke/tokyonight.nvim",
		opts = { transparent = true, styles = { sidebars = "transparent", floats = "transparent" } },
	},
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,
		opts = {
			integrations = {
				blink_cmp = true,
				dap = true,
				dap_ui = true,
				diffview = true,
				dropbar = { enabled = true, color_mode = true },
				flash = true,
				gitsigns = true,
				grug_far = true,
				lsp_trouble = true,
				mason = true,
				markdown = true,
				mini = true,
				native_lsp = {
					enabled = true,
					underlines = {
						errors = { "undercurl" },
						hints = { "undercurl" },
						warnings = { "undercurl" },
						information = { "undercurl" },
					},
				},
				navic = { enabled = false },
				neotest = true,
				neotree = false,
				noice = true,
				overseer = true,
				snacks = true,
				treesitter = true,
				treesitter_context = true,
				which_key = true,
			},
		},
	},
	{ "rose-pine/neovim", name = "rose-pine" },

	{
		"olimorris/onedarkpro.nvim",
		opts = {
			filetypes = {
				go = false,
				ruby = false,
				java = false,
				vue = false,
			},
			plugins = {
				all = false,
				blink_cmp = true,
				codecompanion = true,
				flash_nvim = true,
				gitsigns = true,
				mason = true,
				mini_diff = true,
				mini_icons = true,
				neotest = true,
				nvim_dap = true,
				nvim_dap_ui = true,
				nvim_lsp = true,
				snacks = true,
				trouble = true,
				which_key = true,
			},
		},
	},
	{ "Mofiqul/dracula.nvim" },
	{ "shaunsingh/nord.nvim" },
})
